name: Java CI on Windows

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Start and verify server
        run: |
          # 1. Запуск сервера
          $serverProcess = Start-Process -NoNewWindow -PassThru -FilePath "java" -ArgumentList "-jar .\artifacts\app-mbank.jar"
          Write-Host "Server started with PID: $($serverProcess.Id)"

          # 2. Проверка доступности
          $attempt = 0
          $maxAttempts = 30
          $isReady = $false

          while ($attempt -lt $maxAttempts -and -not $isReady) {
              $attempt++
              try {
                  $response = Invoke-WebRequest -Uri "http://localhost:9999/api/v1/demo/accounts" -UseBasicParsing -ErrorAction Stop
                  if ($response.StatusCode -eq 200) {
                      $isReady = $true
                      Write-Host "Server is ready after $attempt seconds"
                  }
              } catch {
                  Write-Host "Attempt $attempt of $maxAttempts: Server not ready yet..."
                  Start-Sleep -Seconds 1
              }
          }

          if (-not $isReady) {
              Write-Host "Error: Server failed to start within $maxAttempts seconds"
              Stop-Process -Id $serverProcess.Id -Force
              exit 1
          }

      - name: Run tests
        run: .\gradlew.bat test --info --stacktrace

      - name: Stop server
        if: always()
        run: |
          taskkill /IM "java.exe" /F /T 2>&1 | Out-Null
          Write-Host "Server process terminated"
