name: Java CI with Gradle

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Start server
        run: |
          Start-Process -NoNewWindow -FilePath "java" -ArgumentList "-jar .\artifacts\app-mbank.jar"
          Start-Sleep -Seconds 5
          Invoke-WebRequest -Uri "http://localhost:9999/api/v1/demo/accounts" -UseBasicParsing

      - name: Run tests with Gradle
        run: ./gradlew test --info --stacktrace

      - name: Upload test reports
        if: always()
        uses: actions/upload-artifact@v4  # Обновлено до v4
        with:
          name: test-reports
          path: |
            build/reports/tests/test/
            build/test-results/test/
          retention-days: 5  # Автоматическое удаление через 5 дней

      - name: Upload JaCoCo reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-reports
          path: build/reports/jacoco/test/
          retention-days: 5
